### ISSUE TITLE
Extend Python documentation, including framework guides

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#2832]
### What needs to be documented?

The [Python documentation ](https://docs.platform.sh/languages/python.html) can be updated to reflect recent work in a number of frameworks. Managing dependencies, choices of web servers, and other topics can be placed in a shared space for all frameworks under this `/languages/python` section.

For specific frameworks, and building upon the work in https://github.com/platformsh/platformsh-docs/pull/2804, dedicated stack guides can be expanded or created for Django, FastAPI, and Flask. This issue tracks an ongoing effort for many different pieces of better documenting Python framework deployment over several upcoming PRs. 

**Tasks:**

- Python (shared)
   - [x] tweaks and improvements to the Python main reference page structure. https://github.com/platformsh/platformsh-docs/pull/2833
   - [ ] Remove Configuration Reader dependence (https://github.com/platformsh/language-examples) in "Connect services section"
   - [x] managing dependencies: the differences handling pip, pipenv, and poetry https://github.com/platformsh/platformsh-docs/pull/2833
   - [x] web servers: choices and configuration https://github.com/platformsh/platformsh-docs/pull/2833 ASGI options are preferred
   - [ ] web servers II: uwsgi
   - [ ] celery workers configuration
   - [ ] fleet
   - [x] Address Poetry configuration https://github.com/platformsh/platformsh-docs/issues/2983
   - [ ] Utilizing the build cache
- Django
   - [x] primary deployment guide (`/guides/django/deploy`) https://github.com/platformsh/platformsh-docs/pull/2833
   - [x] local development: DDEV + scenarios https://github.com/platformsh/platformsh-docs/pull/2833
   - [x] local development: Docker Compose + scenarios https://github.com/platformsh/platformsh-docs/pull/2833
   - [x] local development: Tethered local + scenarios https://github.com/platformsh/platformsh-docs/pull/2833
   - [ ] Update to Experimental DDEV instructions https://ddev.readthedocs.io/en/latest/users/quickstart/
   - [ ] venv > Virtualenv > Docker > Pipenv > Poetry
   - [ ] code formatters: black > isort > autopep8 > pre-commit
   - [ ] linters: flake8 > black > pylint > mypy
   - [ ] Cloud: AWS > Digital Ocean > Heroku > GCS > PythonAnywhere >> Fly.io
   - [ ] local dev: locally with virtualenv > Docker
   - [ ] CI: GitHub actions > GitLab CI > Jenkins
   - [ ] microservices/decoupled: djangorestframework + React > Vue >> Angular
   - [ ] performance
   - [ ] pytest
   - [ ] mypy, pyright/pylance for type checking
   - [ ] djangoproject.com visibility > blogs > YT
- FastAPI
   - [ ] primary deployment guide (`/guides/fastapi/deploy`)
   - [ ] local development: DDEV + scenarios
   - [ ] local development: Tethered local + scenarios   
   - [ ] microservices/decoupled
   - [ ] performance
- Flask
   - [ ] primary deployment guide (`/guides/flask/deploy`)
   - [ ] local development: DDEV + scenarios
   - [ ] local development: Tethered local + scenarios   
   - [ ] microservices/decoupled
   - [ ] performance
- Development
   - [x] sanitizing data: python specific concerns for PII in non-production environments with a PostgreSQL version of https://docs.platform.sh/development/sanitize-db.html https://github.com/platformsh/platformsh-docs/pull/2833

**Comment by chadwcarlson** [comment]
[Django developer survey results](https://lp.jetbrains.com/django-developer-survey-2022/)
